name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Android SDK
      run: echo y | sdkmanager "platforms;android-33"
    - name: set up JDK 11 and Gradle
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        gradle-version: '7.3.1'
        cache: gradle
    



    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
